server.port=9090
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://mysql:3306/db_unab}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:import.sql
spring.sql.init.data-locations=classpath:auth-seed.sql
spring.jpa.defer-datasource-initialization=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL57Dialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
logging.level.org.hibernate.SQL=debug
